default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: desight
  password: Desight101
  host: localhost
  port: 5432

development:
  <<: *default
  database: desight-dev
  timeout: 5000

test:
  <<: *default
  database: desight-test

production:
  url: <%= ENV['DATABASE_URL'] %>
